# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#from PyQt5.Qt3DExtras import Qt3DExtras
#from PyQt5.Qt3DCore import Qt3DCore

import requests
import sys
import io
import folium
import os
import time
import numpy as np
import urllib.request
import imutils
import struct
import socket
import cv2

from PyQt5 import QtCore, QtGui, QtWidgets, QtOpenGL
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout, QLCDNumber, QHBoxLayout, QVBoxLayout, QHeaderView
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QTimer
from PyQt5.QtCore import *
from PyQt5.QtGui import QImage
from PyQt5.QtGui import*
from qtpy.QtGui import QPainter, QColor, QPen, QBrush, QPixmap
from PyQt5.QtWebEngineWidgets import QWebEngineView

import datetime as dt
import matplotlib
import matplotlib as plt
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as pl
from MplWidget import *

import OpenGL.GL as gl
from OpenGL import GLU
from OpenGL.arrays import vbo

from PIL import Image
import csv
from write_csv import write_csv


paket_numarasi = 0
uydu_statusu = 0
hata_kodu = ['','','','','']
gonderme_saat = 0
basinc1 = 0
basinc2 = 0
yukseklik1 = 0
yukseklik2 = 0
irtifa_farki = 0
inis_hizi = 0
sicaklik = 0
pil_gerilim = 0
gps_latitude = 0
gps_longitude = 0
gps_altitude = 0
pitch = 0
roll = 0
yaw = 0
takim_no = 0
video_aktarim_bilgisi = 0
video = ""
xs = []
ys = []
xs2 = []
ys2 = []
xs3 = []
ys3 = []
xs4 = []
ys4 = []
xs5 = []
ys5 = []
xs6 = []
ys6 = []
xs7 = []
ys7 = []
xs8 = []
ys8 = []
cap = None
out = None
paket_sayisi = 0
telemetri_paketi = []
son_telemetri = []

# url='http://192.168.1.2:8000/stream.mjpg'
 
host = "172.20.10.7"
port = 9889
index = 0 
# yer_istasyonu_socket = socket.socket()
# yer_istasyonu_socket.connect((host,port))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1020)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setBaseSize(QtCore.QSize(5000, 5000))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setIconSize(QtCore.QSize(1920, 1080))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gridLayoutWidget_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 159, 1401, 661))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.yukseklik_gorev_yuku = yukseklik_gorev_yuku_widget(self.gridLayoutWidget_2)
        self.yukseklik_gorev_yuku.setObjectName("yukseklik_gorev_yuku")
        self.gridLayout_2.addWidget(self.yukseklik_gorev_yuku, 0, 1, 1, 1) # sütun 2 satır 1
        self.yukseklik_gorev_yuku.setStyleSheet("background-color: white;")

        self.yukseklik_gorev_yuku_Label = QtWidgets.QLabel(self.centralwidget)
        self.yukseklik_gorev_yuku_Label.setGeometry(QtCore.QRect(671, 173, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.yukseklik_gorev_yuku_Label.setFont(font)
        self.yukseklik_gorev_yuku_Label.setObjectName("yukseklik_gorev_yuku")
        
        self.sicaklik_gorev_yuku = sicaklik_gorev_yuku_widget(self.gridLayoutWidget_2)
        self.sicaklik_gorev_yuku.setObjectName("sicaklik_gorev_yuku")
        self.gridLayout_2.addWidget(self.sicaklik_gorev_yuku, 0, 0, 1, 1) # sütun 1 satır 1
        self.sicaklik_gorev_yuku.setStyleSheet("background-color: white;")

        self.sicaklik_gorev_yuku_Label = QtWidgets.QLabel(self.centralwidget)
        self.sicaklik_gorev_yuku_Label.setGeometry(QtCore.QRect(214, 173, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sicaklik_gorev_yuku_Label.setFont(font)
        self.sicaklik_gorev_yuku_Label.setObjectName("sicaklik_gorev_yuku")
        
        self.inis_hizi_gorev_yuku = inis_hizi_gorev_yuku_widget(self.gridLayoutWidget_2)
        self.inis_hizi_gorev_yuku.setObjectName("inis_hizi_gorev_yuku")
        self.gridLayout_2.addWidget(self.inis_hizi_gorev_yuku, 1, 0, 1, 1) # sütun 1 satır 2 
        self.inis_hizi_gorev_yuku.setStyleSheet("background-color: white;")

        self.inis_hizi_gorev_yuku_Label = QtWidgets.QLabel(self.centralwidget)
        self.inis_hizi_gorev_yuku_Label.setGeometry(QtCore.QRect(207, 395, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.inis_hizi_gorev_yuku_Label.setFont(font)
        self.inis_hizi_gorev_yuku_Label.setObjectName("inis_hizi_gorev_yuku")
        
        self.irtifa_farki = irtifa_farki_widget(self.gridLayoutWidget_2)
        self.irtifa_farki.setObjectName("irtifa_farki")
        self.gridLayout_2.addWidget(self.irtifa_farki, 2, 0, 1, 1) # sütun 1 satır 3
        self.irtifa_farki.setStyleSheet("background-color: white;")

        self.irtifa_farki_Label = QtWidgets.QLabel(self.centralwidget)
        self.irtifa_farki_Label.setGeometry(QtCore.QRect(205, 615, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.irtifa_farki_Label.setFont(font)
        self.irtifa_farki_Label.setObjectName("irtifa_farki")
        
        self.pil_gerilimi_gorev_yuku = pil_gerilimi_gorev_yuku_widget(self.gridLayoutWidget_2)
        self.pil_gerilimi_gorev_yuku.setObjectName("pil_gerilimi_gorev_yuku")
        self.gridLayout_2.addWidget(self.pil_gerilimi_gorev_yuku, 2, 1, 1, 1) # sütun 2 satır 3
        self.pil_gerilimi_gorev_yuku.setStyleSheet("background-color: white;")

        self.pil_gerilimi_gorev_yuku_Label = QtWidgets.QLabel(self.centralwidget)
        self.pil_gerilimi_gorev_yuku_Label.setGeometry(QtCore.QRect(669, 615, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pil_gerilimi_gorev_yuku_Label.setFont(font)
        self.pil_gerilimi_gorev_yuku_Label.setObjectName("pil_gerilimi_gorev_yuku")
        
        self.basinc_gorev_yuku = basinc_gorev_yuku_widget(self.gridLayoutWidget_2)
        self.basinc_gorev_yuku.setObjectName("basinc_gorev_yuku")
        self.gridLayout_2.addWidget(self.basinc_gorev_yuku, 1, 1, 1, 1) # sütun 2 satır 2
        self.basinc_gorev_yuku.setStyleSheet("background-color: white;")

        self.basinc_gorev_yuku_Label = QtWidgets.QLabel(self.centralwidget)
        self.basinc_gorev_yuku_Label.setGeometry(QtCore.QRect(675, 395, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.basinc_gorev_yuku_Label.setFont(font)
        self.basinc_gorev_yuku_Label.setObjectName("basinc_gorev_yuku")
        
        self.yukseklik_tasiyici = yukseklik_tasiyici_widget(self.gridLayoutWidget_2)
        self.yukseklik_tasiyici.setObjectName("yukseklik_tasiyici")
        self.gridLayout_2.addWidget(self.yukseklik_tasiyici, 0, 2, 1, 1) # sütun 3 satır 1
        self.yukseklik_tasiyici.setStyleSheet("background-color: white;")

        self.yukseklik_tasiyici_Label = QtWidgets.QLabel(self.centralwidget)
        self.yukseklik_tasiyici_Label.setGeometry(QtCore.QRect(1122, 173, 130, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.yukseklik_tasiyici_Label.setFont(font)
        self.yukseklik_tasiyici_Label.setObjectName("yukseklik_tasiyici")
        
        self.basinc_tasiyici = basinc_tasiyici_widget(self.gridLayoutWidget_2)
        self.basinc_tasiyici.setObjectName("basinc_tasiyici")
        self.gridLayout_2.addWidget(self.basinc_tasiyici, 1, 2, 1, 1) # sütun 3 satır 2
        self.basinc_tasiyici.setStyleSheet("background-color: white;")

        self.basinc_tasiyici_Label = QtWidgets.QLabel(self.centralwidget)
        self.basinc_tasiyici_Label.setGeometry(QtCore.QRect(1129, 395, 125, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.basinc_tasiyici_Label.setFont(font)
        self.basinc_tasiyici_Label.setObjectName("basinc_tasiyici")
        
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 830, 1901, 163))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.veri_akis_tablosu = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.veri_akis_tablosu.setObjectName("veri_akis_tablosu")
        self.veri_akis_tablosu.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.veri_akis_tablosu.setColumnCount(20)
        self.veri_akis_tablosu.setHorizontalHeaderLabels(str("takim_no;paket_numarasi;uydu_statusu;hata_kodu;gonderme_saat;basinc1;basinc2;yukseklik1;yukseklik2;irtifa_farki;inis_hizi;sicaklik;pil_gerilim;gps1_latitude;gps1_longitude;gps1_altitude;pitch;yaw;roll;video_aktarim_bilgisi").split(";"))
        
        self.veri_akis_tablosu.verticalHeader().hide()
        self.veri_akis_tablosu.horizontalHeader().setStyleSheet("font: bold 7px;")
        self.veri_akis_tablosu.horizontalHeader().setDefaultAlignment(Qt.AlignLeft)
        self.veri_akis_tablosu.horizontalScrollBar().hide()
        self.veri_akis_tablosu.setStyleSheet("font:9px;")
          
        self.veri_akis_tablosu.setColumnWidth(0,59)
        self.veri_akis_tablosu.setColumnWidth(1,98)
        self.veri_akis_tablosu.setColumnWidth(2,95)
        self.veri_akis_tablosu.setColumnWidth(3,45)
        self.veri_akis_tablosu.setColumnWidth(4,60)
        self.veri_akis_tablosu.setColumnWidth(5,53)
        self.veri_akis_tablosu.setColumnWidth(6,51)
        self.veri_akis_tablosu.setColumnWidth(7,71)
        self.veri_akis_tablosu.setColumnWidth(8,77)
        self.veri_akis_tablosu.setColumnWidth(9,89)
        self.veri_akis_tablosu.setColumnWidth(10,77)
        self.veri_akis_tablosu.setColumnWidth(11,84)
        self.veri_akis_tablosu.setColumnWidth(12,38)
        self.veri_akis_tablosu.setColumnWidth(13,32)
        self.veri_akis_tablosu.setColumnWidth(14,31)
        self.veri_akis_tablosu.setColumnWidth(15,80)
        self.veri_akis_tablosu.setColumnWidth(16,151)
        self.veri_akis_tablosu.setColumnWidth(17,171)
        self.veri_akis_tablosu.setColumnWidth(18,191)
        self.veri_akis_tablosu.setColumnWidth(19,201)
        #self.veri_akis_tablosu.setHorizontalHeaderLabels(["takim_no","paket_numarasi","uydu_statusu","hata_kodu","gonderme_saat","basinc1","basinc2","yukseklik1","yukseklik2","irtifa_farki","inis_hizi","sicaklik","pil_gerilim","gps1_latitude","gps1_longitude","gps1_altitude","pitch","yaw","roll","video_aktarim_bilgisi"])
        self.veri_akis_tablosu.horizontalHeader().setStyleSheet("font: bold 9px;")
        self.gridLayout_3.addWidget(self.veri_akis_tablosu, 0, 0, 1, 1)
        
        self.video_stream_widget = VideoStreamWidget('http://172.20.10.3:8000/stream.mjpg')
        self.verticalLayoutWidgetkamera = QtWidgets.QLabel(self.centralwidget)
        self.verticalLayoutWidgetkamera.setGeometry(QtCore.QRect(945, 580, 465, 250))
        self.verticalLayoutWidgetkamera.setObjectName("verticalLayoutWidgetkamera")
        
        self.verticalLayout_kamera = QtWidgets.QVBoxLayout(self.verticalLayoutWidgetkamera)
        self.verticalLayout_kamera.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_kamera.setObjectName("verticalLayout_4")
        self.verticalLayout_kamera.addWidget(self.video_stream_widget)

        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1420, 279, 491, 266)) #1420, 279, 491, 266
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
       
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.verticalLayoutWidget_4)
        self.openGLWidget.setObjectName("openGLWidget")
        self.verticalLayout_4.addWidget(self.openGLWidget)
        self.verticalLayout_4.setAlignment(QtCore.Qt.AlignCenter)

        self.verticalLayoutWidget_4 = Figure()
        self.canvas = FigureCanvas(self.verticalLayoutWidget_4)
        self.verticalLayout_4.addWidget(self.canvas)
        self.ax = self.verticalLayoutWidget_4.add_subplot(111, projection='3d')
        self.ax.set_xlabel('Pitch')
        self.ax.set_ylabel('Yaw')
        self.ax.set_zlabel('Roll')

        pitch = [1, 0, 8, 4, 0]
        yaw = [0, 0, 0, 0, 0]
        roll = [0, 0, 0, 0, 0]
        self.ax.scatter(pitch, yaw, roll)

        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(958, 0, 450, 150))
        self.gridLayoutWidget_5.setObjectName("verticalLayoutWidget_3")


        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1420, 554, 491, 266))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
       
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
       
        self.gps_gorev_yuku = QWebEngineView(self.verticalLayoutWidget_2)
        self.gps_gorev_yuku.setObjectName("gps_gorev_yuku")
        self.verticalLayout_2.addWidget(self.gps_gorev_yuku)
        self.gps_gorev_yuku.setStyleSheet("background-color: white;")

        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.uydu_statusu=QListWidget(self.gridLayoutWidget_5)
        self.uydu_statusu.setObjectName("arayuz_alarm_sistemi")
        self.gridLayout_5.addWidget(self.uydu_statusu, 0, 0, 1, 1)
        self.statu_rengi=QBrush(QColor(0,100,0))#(156, 239, 130)
        self.uydu_statusu.setStyleSheet("font:bold 13px rgba(255, 80, 232, 0.849)")
        self.uydu_statusu.setFont(QFont("Cascadia Mono SemiBold",10))
        self.uydu_statusu.setFixedHeight(150)
        self.uydu_statusu.setFixedWidth(450)
        self.uydu_statusu.setSelectionMode(QListWidget.MultiSelection)
        self.uydu_statusu.setAutoFillBackground(True)
        self.uydu_statusu_baslik=QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.uydu_statusu_baslik=QLabel("UYDU STATÜSÜ")
        self.uydu_statusu_baslik.setFont(QFont("Cascadia Mono SemiBold",14,QFont.Bold))
        self.uydu_statusu_item=["Uçuşa Hazır","Yükselme","Model Uydu İniş","Ayrılma","Görev Yükü İniş","Kurtarma (Görev Yükü'nün Yere Teması)","Paket Video (500 KB) Alındı","Görev Tamamlandı"]
        self.uydu_statusu.setFont(QFont("Cascadia Mono SemiBold",14))
        self.z=0
        for i in self.uydu_statusu_item:
            self.uydu_statusu.addItem(i)
        # for i in range(0,6):
        #     self.uydu_statusu_item(i).setBackground(Qt.transparent)
        # self.uydu_statusu_item(0).setBackground(self.statu_rengi)
        # self.uydu_statusu.setCurrentRow(0)    

        self.uydu_statusu_baslik.setFixedWidth(0)
        self.uydu_statusu_baslik.setFixedHeight(60)
        self.uydu_statusu_baslik.setStyleSheet("background-color: #e6e6e6; border:1px solid #068057")
        self.uydu_statusu.setStyleSheet("background-color: #e6e6e6")

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 10, 127, 127))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
       
        self.Takim_Logosu_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Takim_Logosu_layout.setContentsMargins(0, 0, 0, 0)
        self.Takim_Logosu_layout.setObjectName("Takim_Logosu_layout")
        self.Takim_Logosu = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Takim_Logosu.setText("")
        self.Takim_Logosu.setPixmap(QtGui.QPixmap("logo.jpg"))
        self.Takim_Logosu.setScaledContents(False)
        self.Takim_Logosu.setObjectName("Takim_Logosu")
        self.Takim_Logosu_layout.addWidget(self.Takim_Logosu)

        self.Aras_Yazi1 = QtWidgets.QLabel(self.centralwidget)
        self.Aras_Yazi1.setScaledContents(False)
        self.Aras_Yazi1.setGeometry(QtCore.QRect(1410, 130, 600, 20))
        self.Aras_Yazi1.setObjectName("Aras_Yazi1")
        self.Aras_Yazi1.setText('(Model uydu iniş hızının 12-14 m/s değerleri içerisinde)')

        self.Aras_Yazi2 = QtWidgets.QLabel(self.centralwidget)
        self.Aras_Yazi2.setScaledContents(False)
        self.Aras_Yazi2.setGeometry(QtCore.QRect(1410, 160, 600, 20))
        self.Aras_Yazi2.setObjectName("Aras_Yazi2")
        self.Aras_Yazi2.setText('(Görev yükü iniş hızının 6-8 m/s değerleri içerisinde)')

        self.Aras_Yazi3 = QtWidgets.QLabel(self.centralwidget)
        self.Aras_Yazi3.setScaledContents(False)
        self.Aras_Yazi3.setGeometry(QtCore.QRect(1410, 190, 600, 20))
        self.Aras_Yazi3.setObjectName("Aras_Yazi3")
        self.Aras_Yazi3.setText('(Taşıyıcı basınç verisi alınıyor)')
        
        self.Aras_Yazi4 = QtWidgets.QLabel(self.centralwidget)
        self.Aras_Yazi4.setScaledContents(False)
        self.Aras_Yazi4.setGeometry(QtCore.QRect(1410, 220, 600, 20))
        self.Aras_Yazi4.setObjectName("Aras_Yazi4")
        self.Aras_Yazi4.setText('(Görev yükü konum verisi alınıyor)')

        self.Aras_Yazi5 = QtWidgets.QLabel(self.centralwidget)
        self.Aras_Yazi5.setScaledContents(False)
        self.Aras_Yazi5.setGeometry(QtCore.QRect(1410, 250, 600, 20))
        self.Aras_Yazi5.setObjectName("Aras_Yazi5")
        self.Aras_Yazi5.setText('(Ayrılma gerçekleşti)')
        
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(1420, 20, 80, 100))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")

        self.Aras_1_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.Aras_1_layout.setContentsMargins(0, 0, 0, 0)
        self.Aras_1_layout.setObjectName("Aras_1_layout")
        self.Aras_1 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.Aras_1.setText("")
        
        self.Aras_1.setScaledContents(False)
        self.Aras_1.setObjectName("Aras_1")
        self.Aras_1_layout.addWidget(self.Aras_1) 

        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(1510, 20, 80, 100))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")

        self.Aras_2_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.Aras_2_layout.setContentsMargins(0, 0, 0, 0)
        self.Aras_2_layout.setObjectName("Aras_2_layout")
        self.Aras_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Aras_2.setText("")
        
        self.Aras_2.setScaledContents(False)
        self.Aras_2.setObjectName("Aras_2")
        self.Aras_2_layout.addWidget(self.Aras_2)
        
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(1600, 20, 80, 100))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")

        self.Aras_3_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.Aras_3_layout.setContentsMargins(0, 0, 0, 0)
        self.Aras_3_layout.setObjectName("Aras_3_layout")
        self.Aras_3 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.Aras_3.setText("")
        
        self.Aras_3.setScaledContents(False)
        self.Aras_3.setObjectName("Aras_3")
        self.Aras_3_layout.addWidget(self.Aras_3)  
     
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(1690, 20, 80, 100))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")

        self.Aras_4_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.Aras_4_layout.setContentsMargins(0, 0, 0, 0)
        self.Aras_4_layout.setObjectName("Aras_4_layout")
        self.Aras_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.Aras_4.setText("")
        
        self.Aras_4.setScaledContents(False)
        self.Aras_4.setObjectName("Aras_4")
        self.Aras_4_layout.addWidget(self.Aras_4)

        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(1780, 20, 80, 100))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")

        self.Aras_5_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.Aras_5_layout.setContentsMargins(0, 0, 0, 0)
        self.Aras_5_layout.setObjectName("Aras_5_layout")
        self.Aras_5 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.Aras_5.setText("")
        
        self.Aras_5.setScaledContents(False)
        self.Aras_5.setObjectName("Aras_5")
        self.Aras_5_layout.addWidget(self.Aras_5)
       
        self.text_Aras_no = QtWidgets.QLabel(self.centralwidget)
        self.text_Aras_no.setGeometry(QtCore.QRect(1457, 2, 400, 16))
        self.text_Aras_no.setObjectName("text_Aras_no")


        self.text_takim_no = QtWidgets.QLabel(self.centralwidget)
        self.text_takim_no.setGeometry(QtCore.QRect(150, 1, 450, 60))
        self.text_takim_no.setObjectName("text_takim_no")

        self.text_hata_kodu = QtWidgets.QLabel(self.centralwidget)
        self.text_hata_kodu.setGeometry(QtCore.QRect(1630, 230, 301, 60))
        self.text_hata_kodu.setObjectName("text_hata_kodu")
        self.text_hata_kodu.setText("HATA KODU:")
        

        self.text_hata_kodu_sayısı = QtWidgets.QLabel(self.centralwidget)
        self.text_hata_kodu_sayısı.setGeometry(QtCore.QRect(1720, 230, 301, 60))
        self.text_hata_kodu_sayısı.setObjectName("text_hata_kodu_sayısı")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(146, 29, 531, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
       
        self.gorev_suresi = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.gorev_suresi.setFont(font)
        self.gorev_suresi.setObjectName("gorev_suresi")
        self.gridLayout.addWidget(self.gorev_suresi, 2, 0, 1, 1)

        self.gonderme_saat_label = QLabel(MainWindow)
        self.gonderme_saat_label.setGeometry(220, 80, 230, 80)

        self.gonderme_saat1 = QTimer(MainWindow)
        self.gonderme_saat1.timeout.connect(self.gonderme_paket_uydu_statu_def)
        self.gonderme_saat1.start(1000)
       
        self.paket_sayisi = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.paket_sayisi.setFont(font)
        self.paket_sayisi.setObjectName("paket_sayisi")
        self.gridLayout.addWidget(self.paket_sayisi, 2, 1, 1, 1)

        self.paket_numarasi_label = QLabel(MainWindow)
        self.paket_numarasi_label.setGeometry(362, 80, 230, 80)

        self.paket_numarasi1 = QTimer(MainWindow)
        self.paket_numarasi1.timeout.connect(self.gonderme_paket_uydu_statu_def)
        self.paket_numarasi1.start(1000)
       
        self.uydu_statusu = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.uydu_statusu.setFont(font)
        self.uydu_statusu.setObjectName("uydu_statusu")
        self.gridLayout.addWidget(self.uydu_statusu, 2, 2, 1, 2)

        self.uydu_statusu_label = QLabel(MainWindow)
        self.uydu_statusu_label.setGeometry(505, 80, 230, 80)

        self.uydu_statusu1 = QTimer(MainWindow)
        self.uydu_statusu1.timeout.connect(self.gonderme_paket_uydu_statu_def)
        self.uydu_statusu1.start(1000)
       
        self.ayrilma_komutu = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ayrilma_komutu.setFont(font)
        self.ayrilma_komutu.setObjectName("ayrilma_komutu")
        self.gridLayout.addWidget(self.ayrilma_komutu, 0, 2, 0, 1)
       
        self.gorev_baslat = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.gorev_baslat.setFont(font)
        self.gorev_baslat.setObjectName("gorev_baslat")
        self.gridLayout.addWidget(self.gorev_baslat, 0, 1, 0, 1)

        self.baglanti_kur = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.baglanti_kur.setFont(font)
        self.baglanti_kur.setObjectName("baglanti_kur")
        self.gridLayout.addWidget(self.baglanti_kur, 0, 0, 0, 1)
        
       
        # self.sd_kart_yukle = QtWidgets.QPushButton(self.gridLayoutWidget)
        # font = QtGui.QFont()
        # font.setBold(True)
        # font.setUnderline(False)
        # font.setWeight(75)
        # self.sd_kart_yukle.setFont(font)
        # self.sd_kart_yukle.setAutoDefault(False)
        # self.sd_kart_yukle.setFlat(False)
        # self.sd_kart_yukle.setObjectName("sd_kart_yukle")
        # self.gridLayout.addWidget(self.sd_kart_yukle, 0, 2, 1, 1)
       
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(610, 40, 311, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
       
        self.dosya_sec = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.dosya_sec.setObjectName("dosya_sec")
       
        self.ucnokta_dosya_secimi = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ucnokta_dosya_secimi.setFont(font)
        self.ucnokta_dosya_secimi.setObjectName("ucnokta_dosya_secimi")
        self.horizontalLayout.addWidget(self.ucnokta_dosya_secimi)
       
        self.gonder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.gonder.setFont(font)
        self.gonder.setObjectName("gonder")
        self.horizontalLayout.addWidget(self.gonder)
       
        self.video_aktarimi = QtWidgets.QLabel(self.centralwidget)
        self.video_aktarimi.setGeometry(QtCore.QRect(600, 20, 131, 16))
        self.video_aktarimi.setObjectName("video_aktarimi")

        self.sicaklik_gorev_yuku.raise_()
        self.pil_gerilimi_gorev_yuku.raise_()
        self.inis_hizi_gorev_yuku.raise_()
        self.yukseklik_gorev_yuku.raise_()
        self.yukseklik_tasiyici.raise_()
        self.irtifa_farki.raise_()
        self.basinc_gorev_yuku.raise_()
        self.basinc_tasiyici.raise_()
        #self.openGLWidget.raise_()
        self.gps_gorev_yuku.raise_()
        self.gorev_baslat.raise_()
        self.ayrilma_komutu.raise_()
        self.baglanti_kur.raise_()
        self.gorev_suresi.raise_()
        self.paket_sayisi.raise_()
        self.paket_numarasi_label.raise_()
        self.uydu_statusu.raise_()
        self.uydu_statusu_label.raise_()
        self.ucnokta_dosya_secimi.raise_()
        self.gonder.raise_()
        self.veri_akis_tablosu.raise_()
        # self.arayuz_alarm_sistemi.raise_()
        
        self.gorev_baslat.clicked.connect(self.write_csv)
        self.ayrilma_komutu.clicked.connect(self.baglanti_kur_def)
        # self.baglanti_kur.clicked.connect(self.baglanti_kur_def)
        self.ucnokta_dosya_secimi.clicked.connect(self.ucnokta_dosya_secimi_def)
        self.gonder.clicked.connect(self.sendFifthCommand)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "RHEA MODEL UYDU TAKIMI YER İSYASYONU"))
        
        #self.text_Kullanici_paneli.setText(_translate("MainWindow", "Kullanıcı Paneli                                          "))
        self.text_takim_no.setText(_translate("MainWindow", "Takım Adı: RHEA  Takım No: 134301"))
        self.gorev_suresi.setText(_translate("MainWindow", "   Görev Süresi"))
        self.paket_sayisi.setText(_translate("MainWindow", "   Paket Sayısı"))
        self.uydu_statusu.setText(_translate("MainWindow", "   Uydu Statüsü"))
        self.ayrilma_komutu.setText(_translate("MainWindow", "Ayrılma Komutu"))
        self.gorev_baslat.setText(_translate("MainWindow", "Başlat"))
        self.baglanti_kur.setText(_translate("MainWindow", "Bağlantı Kur"))
        self.dosya_sec.setText(_translate("MainWindow", "Dosya Seç:"))
        self.ucnokta_dosya_secimi.setText(_translate("MainWindow", "..."))
        self.gonder.setText(_translate("MainWindow", "Gönder"))
        self.video_aktarimi.setText(_translate("MainWindow", "Video Aktarımı"))
        self.yukseklik_gorev_yuku_Label.setText(_translate("MainWindow", "Yükseklik (m)"))
        self.yukseklik_tasiyici_Label.setText(_translate("MainWindow", "Taşıyıcı Yükseklik (m)"))
        self.sicaklik_gorev_yuku_Label.setText(_translate("MainWindow", "Sıcaklık (°C)"))
        self.basinc_gorev_yuku_Label.setText(_translate("MainWindow", "Basınç (Pa)"))
        self.basinc_tasiyici_Label.setText(_translate("MainWindow", "Taşıyıcı Basınç (Pa)"))
        self.inis_hizi_gorev_yuku_Label.setText(_translate("MainWindow", "İniş Hızı (m/s)"))
        self.pil_gerilimi_gorev_yuku_Label.setText(_translate("MainWindow", "Pil Gerilimi (V)"))
        self.irtifa_farki_Label.setText(_translate("MainWindow", "İrtifa Farkı (m)"))
        self.text_Aras_no.setText(_translate("MainWindow", "1.        2.        3.        4.        5."))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
       
        self.GPSTRACKING() 
        self.update_graph()
        self.update_graph2()
        self.update_graph3()
        self.update_graph4()
        self.update_graph5()
        self.update_graph6()
        self.update_graph7()
        self.update_graph8()
        self.timers()
        # self.createTable()
        self.hata_kodu_def1()
        self.hata_kodu_def2()
        self.hata_kodu_def3()
        self.hata_kodu_def4()
        self.hata_kodu_def5()
        self.hata_kodu_yazi1()
        self.hata_kodu_yazi2()
        self.hata_kodu_yazi3()
        self.hata_kodu_yazi4()
        self.hata_kodu_yazi5()
        # self.hata_kodu_yazi6()
        self.text_hata_kodu_sayısı_def()
        self.timers()
    
    def baglanti_kur_def(self):
        global yer_istasyonu_socket,son_telemetri
        yer_istasyonu_socket = socket.socket()
        yer_istasyonu_socket.connect((host,port))
        komut = "0"
        yer_istasyonu_socket.send(komut.encode()) 
        telemetri_paketi = yer_istasyonu_socket.recv(1024).decode() #açılacak
        son_telemetri = telemetri_paketi.split(",") # açılacak
        
    def update_graph(self):
        global xs
        global ys

        global paket_sayisi
        global sicaklik
        xs.append(paket_sayisi)
        ys.append(sicaklik)

        xs = xs[-6:]
        ys = ys[-6:]

        self.sicaklik_gorev_yuku.canvas.axes.clear()
        self.sicaklik_gorev_yuku.canvas.axes.plot(xs, ys, linewidth=2, label="{1}")
        self.sicaklik_gorev_yuku.canvas.draw()
        paket_sayisi += 1

    def update_graph2(self):
        global xs2
        global ys2

        global paket_sayisi
        global pil_gerilim
        xs2.append(paket_sayisi)
        ys2.append(pil_gerilim)

        xs2 = xs2[-6:]
        ys2 = ys2[-6:]

        self.pil_gerilimi_gorev_yuku.canvas.axes.clear()
        self.pil_gerilimi_gorev_yuku.canvas.axes.plot(xs2, ys2, linewidth=2, label="{1}")
        self.pil_gerilimi_gorev_yuku.canvas.draw()

    def update_graph3(self):
        global xs3
        global ys3

        global paket_sayisi
        global inis_hizi
        xs3.append(paket_sayisi)
        ys3.append(inis_hizi)

        xs3 = xs3[-6:]
        ys3 = ys3[-6:]

        self.inis_hizi_gorev_yuku.canvas.axes.clear()
        self.inis_hizi_gorev_yuku.canvas.axes.plot(xs3, ys3, linewidth=2, label="{1}")
        self.inis_hizi_gorev_yuku.canvas.draw()

    def update_graph4(self):
        global xs4
        global ys4

        global paket_sayisi
        global yukseklik1
        xs4.append(paket_sayisi)
        ys4.append(yukseklik1)

        xs4 = xs4[-6:]
        ys4 = ys4[-6:]

        self.yukseklik_gorev_yuku.canvas.axes.clear()
        self.yukseklik_gorev_yuku.canvas.axes.plot(xs4, ys4, linewidth=2, label="{1}")
        self.yukseklik_gorev_yuku.canvas.draw()

    def update_graph5(self):
        global xs5
        global ys5

        global paket_sayisi
        global yukseklik2
        xs5.append(paket_sayisi)
        ys5.append(yukseklik2)

        xs5 = xs5[-6:]
        ys5 = ys5[-6:]

        self.yukseklik_tasiyici.canvas.axes.clear()
        self.yukseklik_tasiyici.canvas.axes.plot(xs5, ys5, linewidth=2, label="{1}")
        self.yukseklik_tasiyici.canvas.draw()

    def update_graph6(self):
        global xs6
        global ys6

        global paket_sayisi
        global irtifa_farki
        xs6.append(paket_sayisi)
        ys6.append(irtifa_farki)

        xs6 = xs6[-6:]
        ys6 = ys6[-6:]

        self.irtifa_farki.canvas.axes.clear()
        self.irtifa_farki.canvas.axes.plot(xs6, ys6, linewidth=2, label="{1}")
        self.irtifa_farki.canvas.draw()

    def update_graph7(self):
        global xs7
        global ys7

        global paket_sayisi
        global basinc1
        xs7.append(paket_sayisi)
        ys7.append(basinc1)

        xs7 = xs7[-6:]
        ys7 = ys7[-6:]

        self.basinc_gorev_yuku.canvas.axes.clear()
        self.basinc_gorev_yuku.canvas.axes.plot(xs7, ys7, linewidth=2, label="{1}")
        self.basinc_gorev_yuku.canvas.draw()

    def update_graph8(self):
        global xs8
        global ys8

        global paket_sayisi
        global basinc2
        xs8.append(paket_sayisi)
        ys8.append(basinc2)

        xs8 = xs8[-6:]
        ys8 = ys8[-6:]

        self.basinc_tasiyici.canvas.axes.clear()
        self.basinc_tasiyici.canvas.axes.plot(xs8, ys8, linewidth=2, label="{1}")
        self.basinc_tasiyici.canvas.draw()

    def hata_kodu_def1(self):
        global hata_kodu
        if hata_kodu[0] == '1':
            self.Aras_1.setPixmap(QPixmap('GREEN.png'))
        else:
            self.Aras_1.setPixmap(QPixmap('RED.png'))

    def hata_kodu_def2(self):
        global hata_kodu
        if hata_kodu[1] == '1':
            self.Aras_2.setPixmap(QPixmap('GREEN.png'))
        else:
            self.Aras_2.setPixmap(QPixmap('RED.png'))
    
    def hata_kodu_def3(self):
        global hata_kodu
        if hata_kodu[2] == '1':
            self.Aras_3.setPixmap(QPixmap('GREEN.png'))
        else:
            self.Aras_3.setPixmap(QPixmap('RED.png'))
    
    def hata_kodu_def4(self):
        global hata_kodu
        if hata_kodu[3] == '1':
            self.Aras_4.setPixmap(QPixmap('GREEN.png'))
        else:
            self.Aras_4.setPixmap(QPixmap('RED.png'))
    
    def hata_kodu_def5(self):
        global hata_kodu
        if hata_kodu[4] == '1':
            self.Aras_5.setPixmap(QPixmap('GREEN.png'))
        else:
            self.Aras_5.setPixmap(QPixmap('RED.png'))

    
    def hata_kodu_yazi1(self):
        global hata_kodu
        if hata_kodu[0] == '1':
            text1 = '(Model uydu iniş hızının 12-14 m/s değerleri içerisinde)'
            self.Aras_Yazi1.setText(text1)
        else:
            text2 = '(Model uydu iniş hızının 12-14 m/s değerleri dışında)'
            self.Aras_Yazi1.setText(text2)

    def hata_kodu_yazi2(self):
        global hata_kodu
        if hata_kodu[1] == '1':
            text3 = '(Görev yükü iniş hızının 6-8 m/s değerleri içerisinde)'
            self.Aras_Yazi2.setText(text3)
        else:
            text4 = '(Görev yükü iniş hızının 6-8 m/s değerleri dışında)'
            self.Aras_Yazi2.setText(text4)
    
    def hata_kodu_yazi3(self):
        global hata_kodu
        if hata_kodu[2] == '1':
            text5 = '(Taşıyıcı basınç verisi alınıyor)'
            self.Aras_Yazi3.setText(text5)
        else:
            text6 = '(Taşıyıcı basınç verisi alınamıyor)'
            self.Aras_Yazi3.setText(text6)
    
    def hata_kodu_yazi4(self):
        global hata_kodu
        if hata_kodu[3] == '1':
            text7 = '(Görev yükü konum verisi alınıyor)'
            self.Aras_Yazi4.setText(text7)
        else:
            text8 = '(Görev yükü konum verisi alınamıyor)'
            self.Aras_Yazi4.setText(text8)
    
    def hata_kodu_yazi5(self):
        global hata_kodu
        if hata_kodu[4] == '1':
            text9 = '(Ayrılma gerçekleşti)'
            self.Aras_Yazi5.setText(text9)
        else:
            text10 = '(Ayrılma gerçekleşmedi)'
            self.Aras_Yazi5.setText(text10)

    # def hata_kodu_yazi6(self):
        # global hata_kodu
        # if hata_kodu[0,1,2,3,4] == '1':
        #     text10 = '(Problemsiz Uçuş Durumu)'
            # self.Aras_Yazi5.setText(text10)

    def text_hata_kodu_sayısı_def(self):
        global hata_kodu
        
        display_text10 = str(hata_kodu)
        self.text_hata_kodu_sayısı.setText(display_text10)

    def gonderme_paket_uydu_statu_def(self):
        global gonderme_saat, paket_numarasi, uydu_statusu
    
        display_text1 = str(gonderme_saat)
        self.gonderme_saat_label.setText(display_text1)

        display_text2 = str(paket_numarasi)
        self.paket_numarasi_label.setText(display_text2)

        display_text3 = str(uydu_statusu)
        self.uydu_statusu_label.setText(display_text3)

    # def baglanti_kur_def(self):
    #     global yer_istasyonu_socket
    #     yer_istasyonu_socket = socket.socket()
    #     yer_istasyonu_socket.connect((host,port))
    #     komut = "1"
    #     yer_istasyonu_socket.send(komut.encode())


    def gorev_baslat_def(self):
        
        
        getData



    def sendSecondCommand(self):
        global yer_istasyonu_socket
        komut = "3"
        yer_istasyonu_socket.send(komut.encode())

    def sendFourthCommand(self):
        global yer_istasyonu_socket
        komut = "4"
        yer_istasyonu_socket.send(komut.encode())

    def sendFifthCommand(self):
        global yer_istasyonu_socket,video
        komut = "5 "+str(len(video))
        yer_istasyonu_socket.send(komut.encode())
        yer_istasyonu_socket.send(video)

        #dThread = Thread(target=self.download())
        #dThread.start()
        # download = DownloadVideo()
        # download.start()
        # download.dsignal.connect(self.downbitti)               
    
    def download(self):
        global yer_istasyonu_socket,video
        komut = "6 "+str(len(video))
        yer_istasyonu_socket.send(komut.encode())
        yer_istasyonu_socket.send(video)
        #self.dsignal.emit(100)

    def downbitti(self):
        self.video_aktarimi.setText("Evet")    

    def write_csv(data):
            global telemetri_paketi
            with open('telemetri_verileri', 'a') as outfile:
                writer = csv.writer(outfile)
                writer.writerow([data]) 

    
    def getData(self ):
        global yer_istasyonu_socket,index
        global paket_numarasi,uydu_statusu,hata_kodu,gonderme_saat,basinc1,basinc2,yukseklik1,yukseklik2,irtifa_farki,inis_hizi,sicaklik,pil_gerilim,gps_latitude,gps_longitude,gps_altitude,pitch,yaw,roll,takim_no,video_aktarim_bilgisi
        global telemetri_paketi,son_telemetri
        komut = "0"
        # yer_istasyonu_socket.send(komut.encode()) 
        # telemetri_paketi = yer_istasyonu_socket.recv(1024).decode() #açılacak
        # son_telemetri = telemetri_paketi.split(",") # açılacak
        # self.updTable.usignal.connect(self.bitti) 
        
        print(telemetri_paketi)
        # son_telemetri = telemetri_paketi.split(",") # açılacak
        write_csv(son_telemetri)
        
        self.updTable = UpdateTable(self.veri_akis_tablosu,son_telemetri)  
        self.updTable.start()
        self.veri_akis_tablosu.update()
        self.veri_akis_tablosu.scrollToItem(self.veri_akis_tablosu.itemAt(index,0))
        self.veri_akis_tablosu.scrollToItem(self.veri_akis_tablosu.item(index,0))
        index +=1

        # takim_no = int(son_telemetri[0])
        # paket_numarasi = int(son_telemetri[1])
        # # self.paket_sayisiLabel.setText(str(paket_numarasi))
        # uydu_statusu = int(son_telemetri[2])
        # # self.statuNoLabel.setText(str(uydu_statusu))
        # hata_kodu = str(son_telemetri[3])
        # gonderme_saat = float(son_telemetri[4])
        # basinc1 = float(son_telemetri[5])
        # basinc2 = float(son_telemetri[6])
        # yukseklik1 = float(son_telemetri[7])
        # yukseklik2 = float(son_telemetri[8])
        # irtifa_farki = float(son_telemetri[9])
        # inis_hizi = float(son_telemetri[10])
        # sicaklik = float(son_telemetri[11])
        # pil_gerilim = float(son_telemetri[12])
        # gps_latitude,gps_longitude,gps_altitude = float(son_telemetri[13]), float(son_telemetri[14]), float(son_telemetri[15])
        # pitch,yaw,roll = float(son_telemetri[16]), float(son_telemetri[17]), float(son_telemetri[18])
        # # self.glWidget.setRotX(pitch)   
        # # self.glWidget.setRotY(roll) GL WIDGET İÇİN BURADA DÜZGÜN ATAMA YAPILACAK
        # # self.glWidget.setRotZ(yaw)
        # video_aktarim_bilgisi = int(son_telemetri[19])

    def timers(self):

        self.timer0 = QtCore.QTimer()
        self.timer0.setInterval(1000)
        self.timer0.timeout.connect(self.getData)
        self.timer0.start()

        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.update_graph)
        self.timer.start()

        self.timer2 = QtCore.QTimer()
        self.timer2.setInterval(1000)
        self.timer2.timeout.connect(self.update_graph2)
        self.timer2.start()

        self.timer3 = QtCore.QTimer()
        self.timer3.setInterval(1000)
        self.timer3.timeout.connect(self.update_graph3)
        self.timer3.start()

        self.timer4 = QtCore.QTimer()
        self.timer4.setInterval(1000)
        self.timer4.timeout.connect(self.update_graph4)
        self.timer4.start()

        self.timer5 = QtCore.QTimer()
        self.timer5.setInterval(1000)
        self.timer5.timeout.connect(self.update_graph5)
        self.timer5.start()

        self.timer6 = QtCore.QTimer()
        self.timer6.setInterval(1000)
        self.timer6.timeout.connect(self.update_graph6)
        self.timer6.start()
        
        self.timer7 = QtCore.QTimer()
        self.timer7.setInterval(1000)
        self.timer7.timeout.connect(self.update_graph7)
        self.timer7.start()
        
        self.timer8 = QtCore.QTimer()
        self.timer8.setInterval(1000)
        self.timer8.timeout.connect(self.update_graph8)
        self.timer8.start()

        # self.timer9 = QtCore.QTimer()    OPENGL WIDGET
        # self.timer9.setInterval(20)
        # self.timer9.timeout.connect(self.glWidget.updateGL)
        # self.timer9.start()

        self.timer10 = QtCore.QTimer()
        self.timer10.setInterval(1000)
        self.timer10.timeout.connect(self.GPS1)
        self.timer10.start()

        self.timer11 = QtCore.QTimer()
        self.timer11.setInterval(1000)
        self.timer11.timeout.connect(self.hata_kodu_def1)
        self.timer11.start()

        self.timer12 = QtCore.QTimer()
        self.timer12.setInterval(1000)
        self.timer12.timeout.connect(self.hata_kodu_def2)
        self.timer12.start()

        self.timer13 = QtCore.QTimer()
        self.timer13.setInterval(1000)
        self.timer13.timeout.connect(self.hata_kodu_def3)
        self.timer13.start()

        self.timer14 = QtCore.QTimer()
        self.timer14.setInterval(1000)
        self.timer14.timeout.connect(self.hata_kodu_def4)
        self.timer14.start()

        self.timer15 = QtCore.QTimer()
        self.timer15.setInterval(1000)
        self.timer15.timeout.connect(self.hata_kodu_def5)
        self.timer15.start()

        self.timer16 = QtCore.QTimer()
        self.timer16.setInterval(1000)
        self.timer16.timeout.connect(self.hata_kodu_yazi1)
        self.timer16.start()

        self.timer17 = QtCore.QTimer()
        self.timer17.setInterval(1000)
        self.timer17.timeout.connect(self.hata_kodu_yazi2)
        self.timer17.start()

        self.timer18 = QtCore.QTimer()
        self.timer18.setInterval(1000)
        self.timer18.timeout.connect(self.hata_kodu_yazi3)
        self.timer18.start()

        self.timer19 = QtCore.QTimer()
        self.timer19.setInterval(1000)
        self.timer19.timeout.connect(self.hata_kodu_yazi4)
        self.timer19.start()

        self.timer20 = QtCore.QTimer()
        self.timer20.setInterval(1000)
        self.timer20.timeout.connect(self.hata_kodu_yazi5)
        self.timer20.start()

    def bitti(self,val):
        print(val)    
    
    def GPS1(self):
        global gps_latitude,gps_longitude
        folium.Marker([gps_latitude,gps_longitude]).add_to(self.m)

        data = io.BytesIO() 
        self.m.save(data, close_file=False)
        self.gps_gorev_yuku.setHtml(data.getvalue().decode())
        return

    def GPSTRACKING(self):
        coordinate = (gps_latitude, gps_longitude)
        self.m = folium.Map(
            tiles='openstreetmap', 
            zoom_start=12,
            location=coordinate
        )
        folium.Marker([gps_latitude, gps_longitude]).add_to(self.m)
        
        data = io.BytesIO()
        self.m.save(data, close_file=False)
        self.gps_gorev_yuku.setHtml(data.getvalue().decode())

    def ucnokta_dosya_secimi_def(self):
        global video
        file_filter = 'Data File (*.mkv *mp4 *.avi);; Video File (*.mkv *.avi)'
        response = QFileDialog.getOpenFileName(
            parent=self.ucnokta_dosya_secimi_def,
            caption='Select a data file',
            directory=os.getcwd(),
            filter=file_filter,
            initialFilter='Video File (*.mkv *.avi)'
        )
        print(response[0])
        
        with open(response[0],"rb") as f:
            video = f.read()
            print(len(video))

class UpdateTable(QtCore.QThread) :
    def __init__(self, table,arr):
        super(UpdateTable,self).__init__()
        self.table = table
        self.arr =arr
    usignal = QtCore.pyqtSignal(int)
    def run(self):
            global index
            # self.table.setRowCount(10090)
            # self.table.setItem(index,0, QTableWidgetItem(self.arr[0])) 
            # self.table.setItem(index,1, QTableWidgetItem(self.arr[1]))
            # self.table.setItem(index,2, QTableWidgetItem(self.arr[2]))
            # self.table.setItem(index,3, QTableWidgetItem(self.arr[3]))
            # self.table.setItem(index,4, QTableWidgetItem(self.arr[4]))
            #self.table.setItem(index,5, QTableWidgetItem(self.arr[5]))
            # self.table.setItem(index,6, QTableWidgetItem(self.arr[6]))
            # self.table.setItem(index,7, QTableWidgetItem(self.arr[7]))
            # self.table.setItem(index,8, QTableWidgetItem(self.arr[8]))
            # self.table.setItem(index,9, QTableWidgetItem(self.arr[9]))
            # self.table.setItem(index,10, QTableWidgetItem(self.arr[10]))
            # self.table.setItem(index,11, QTableWidgetItem(self.arr[11]))
            # self.table.setItem(index,12, QTableWidgetItem(self.arr[12]))
            # self.table.setItem(index,13, QTableWidgetItem(self.arr[13]))
            # self.table.setItem(index,14, QTableWidgetItem(self.arr[14]))
            # self.table.setItem(index,15, QTableWidgetItem(self.arr[15]))
            # self.table.setItem(index,16, QTableWidgetItem(self.arr[16]))
            # self.table.setItem(index,17, QTableWidgetItem(self.arr[17]))
            # self.table.setItem(index,18, QTableWidgetItem(self.arr[18]))
            # self.table.setItem(index,19, QTableWidgetItem(self.arr[19]))
            # self.usignal.emit(100)

class VideoStreamWidget(QWidget):
    def __init__(self, url, parent=None):
        super().__init__(parent)

        self.video_label = QLabel(self)
        self.video_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_kamera = QVBoxLayout(self)
        self.verticalLayout_kamera.addWidget(self.video_label)
        self.setLayout(self.verticalLayout_kamera)

        self.video_capture = cv2.VideoCapture(url)

        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(50)

    def update_frame(self):
        ret, frame = self.video_capture.read()

        if not ret:
            return

        frame = imutils.resize(frame, width=640)

        height, width, channel = frame.shape
        bytes_per_line = 3 * width
        q_image = QImage(frame.data, width, height, bytes_per_line, QImage.Format_RGB888).rgbSwapped()

        self.video_label.setPixmap(QPixmap.fromImage(q_image))

    def closeEvent(self, event):
        self.video_capture.release()
        super().closeEvent(event)

url = 'http://172.20.10.3:8000/stream.mjpg'
filename = 'haken.avi'

def save_video(url, filename):
    # Send a GET request to the video URL
    response = requests.get(url, stream=True)
    
    # Open a file in binary mode to write the video data to
    with open(filename, 'wb') as f:
        # Iterate over the response content in chunks and write to file
        for chunk in response.iter_content(chunk_size=1024):
            if chunk:
                f.write(chunk)

# save_video(url, filename)

# def write_csv(data):
#     global telemetri_paketi
#     with open('telemetri_verileri', 'a') as outfile:
#         writer = csv.writer(outfile)
#         writer.writerow([data])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
   
    sys.exit(app.exec_())